FROM mcr.microsoft.com/playwright/python:v1.47.0-jammy

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev xvfb \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip setuptools wheel && \
    pip install --no-cache-dir -r requirements.txt

RUN playwright install chromium

COPY . .

# Xvfb potreban za headful Playwright
CMD ["sh", "-c", "Xvfb :99 -screen 0 1440x900x24 & sleep 2 && celery -A app.workers.celery_app.celery worker -l info --concurrency=4"]